services:
  - type: web
    name: flask-shop
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://...
